### ISSUE TITLE
Dockerfile: gems should be pinned to specific versions + http gem should be updateable from a separate file

### ISSUE THREAD

**Issue by OriHoch** [CloudWebManage/cwm-worker-logger#2]
I want to make sure we use a specific set of versions every time we build the Dockerfile, so we won't have unexpected problems / upgrades.

Please add a specific version specifier to all gems installed in the Dockerfile

In addition, I want to have the option to automatically update the http input plugin gem from CI/CD process. This can be done by creating a file e.g. `fluent-plugin-http-cwm.version` and then in the Dockerfile, COPY that file before the gem install script and do something like this: `gem install fluent-plugin-http-cwm==$(cat fluent-plugin-http-cwm.version)`

**Comment by iamazeem** [comment]
Sure. I'll pin the versions for S3 and ElasticSearch gems.

Regarding `fluent-plugin-http-cwm`'s version, how about leaving it like that?
The latest/newest published gem will automatically be installed in the absence of a version specifier.

**Comment by OriHoch** [comment]
there are a few reasons:
1. to know exactly which version is installed, when it was updated, per each git commit
2. allow to rollback to a previous version
3. prevent problems where latest gem is not yet available so we may get previous version, or other possible problems depending on the gem repository

**Comment by iamazeem** [comment]
Added in #6.
