### ISSUE TITLE
Add CI/CD for the http input plugin gem

### ISSUE THREAD

**Issue by OriHoch** [CloudWebManage/cwm-worker-logger#3]
In the http input plugin repository there should be a github workflow which does the following on every push to main branch:

1. Publish the gem
2. Update a file with the published version in the cwm-worker-logger repository (see #2)

We do something like this here - https://github.com/CloudWebManage/cwm-worker-operator/blob/master/bin/helm_publish.sh

You just need to provide the DEPLOY_KEY env var secret, which is an ssh private key. The public key is then added to the target repository you want to update as a deploy key (in github repo settings).

**Comment by iamazeem** [comment]
@OriHoch: Regarding publishing the gem, shouldn't this be on tagging the `main` branch or pushing to it is fine?

**Comment by OriHoch** [comment]
I usually do it that way, but if you want to do it from a tag, that's fine too

**Comment by iamazeem** [comment]
Added this functionality with `publish` workflow:
https://github.com/iamAzeem/fluent-plugin-http-cwm/blob/main/.github/workflows/publish.yml

**Comment by OriHoch** [comment]
:+1:
