### ISSUE TITLE
Add automated unit and integration tests for fluent-plugin-http-cwm and cwm-worker-logger respectively

### ISSUE THREAD

**Issue by OriHoch** [CloudWebManage/cwm-worker-logger#4]
Please add some tests which should run with GitHub workflow on every commit (doesn't have to be 100% full coverage, just make some sanity checks so we can be fairly confident it works after making changes)

* Ruby unit tests - in the http input plugin repository
* Integration / end to end test - in the cwm-worker-logger repository - this can be a bash script which creates some logs and checks that data is available on Redis (no need to test Elasticsearch / S3). In other repositories we use pytest, so if you want you can use that, e.g. - https://github.com/CloudWebManage/cwm-worker-operator/tree/master/tests https://github.com/CloudWebManage/cwm-worker-operator/blob/master/.github/workflows/ci.yml

**Comment by iamazeem** [comment]
The unit tests for `fluent-plugin-http-cwm` have been added.
CI run: https://github.com/iamAzeem/fluent-plugin-http-cwm/actions/runs/515389574
Code coverage percentage: 90+

---

The integration tests for `cwm-worker-logger` have also been added.
CI run: https://github.com/CloudWebManage/cwm-worker-logger/runs/1782064708
