### ISSUE TITLE
integrate the logger with the docker-compose in cwm-worker-deployment-minio

### ISSUE THREAD

**Issue by OriHoch** [CloudWebManage/cwm-worker-logger#5]
[cwm-worker-deployment-minio](https://github.com/CloudWebManage/cwm-worker-deployment-minio) contains the minio deployment. It currently has a metrics-logger based on Python, it should be replaced with the cwm-worker-logger container.

Please update the docker-compose.yaml in that repository to use the cwm-worker-logger, you can add a fluentd configuration which only updates Redis.

**Comment by iamazeem** [comment]
Integrated with https://github.com/CloudWebManage/cwm-worker-logger/commit/447799904d2df97768650c93844281485ec4d3d4 and https://github.com/CloudWebManage/cwm-worker-deployment-minio/pull/3.
