### ISSUE TITLE
integrate with the helm chart at cwm-worker-deployment-minio

### ISSUE THREAD

**Issue by OriHoch** [CloudWebManage/cwm-worker-logger#8]
The logger is integrated into the rest of the architecture via the helm chart at [CloudWebManage/cwm-worker-deployment-minio](https://github.com/CloudWebManage/cwm-worker-deployment-minio)/helm

The project README has instructions on how to run the helm chart locally

The chart needs to be changed to use the cwm-worker-logger container, and the values.yaml for this chart needs to support setting the relevant configurations.

Possible options to implement it:

* Add a configmap which uses the helm templating language to create the relevant fluentd.conf based on configurations from the values.yaml. Example of a similar implementation for nginx: [configmap](https://github.com/hasadna/hasadna-k8s/blob/master/charts-external/odata/templates/nginx-configmap.yaml) [mounting it into a deployment](https://github.com/hasadna/hasadna-k8s/blob/master/charts-external/odata/templates/nginx-deployment.yaml#L48)
* Change the cwm-worker-logger container to accept env vars which modify the configuration

**Comment by iamazeem** [comment]
@OriHoch:
Kindly review the PR: https://github.com/CloudWebManage/cwm-worker-deployment-minio/pull/4

The settings can now be configured via environment variables.
The [configuration files](https://github.com/CloudWebManage/cwm-worker-logger/tree/main/config) for [ES](https://github.com/CloudWebManage/cwm-worker-logger/blob/main/config/cwm-fluent-es.conf) and [S3](https://github.com/CloudWebManage/cwm-worker-logger/blob/main/config/cwm-fluent-s3.conf) have been updated to accommodate the environment variables.
The log target can be switched by selecting the required one via the `FLUENTD_CONF` environment variable in the deployments. 

Default example: https://github.com/CloudWebManage/cwm-worker-logger/blob/0e3a6d8c16d28f032fdd8ac3c19e64c10376f9cc/docker-compose.yaml#L12

**Comment by OriHoch** [comment]
great work! thanks
