### ISSUE TITLE
CI should build and push the logger worker image

### ISSUE THREAD

**Issue by OriHoch** [CloudWebManage/cwm-worker-logger#9]
Need to add the following to the cwm-worker-logger CI after successfull tests:
* on every commit:
  * build the cwm-worker-logger docker image
  * push to github packages and tag with the git SHA
* on push to main branch only:
  * push to github package with tag latest

**Comment by iamazeem** [comment]
Added. Please review.
Workflow: https://github.com/CloudWebManage/cwm-worker-logger/blob/main/.github/workflows/ci.yml
Run: https://github.com/CloudWebManage/cwm-worker-logger/runs/1814738098?check_suite_focus=true
Packages: https://github.com/orgs/CloudWebManage/packages?repo_name=cwm-worker-logger

**Comment by iamazeem** [comment]
Would there be two packages in the case of the `main` branch: 1) with `SHA`, and 2) with the `latest` tag?

**Comment by OriHoch** [comment]
it will be a single package with different tags - 
* latest tag - always updated on push to main
* SHA tag - new tag created on every push to any branch

**Comment by OriHoch** [comment]
on push to main, both tags will be updated

**Comment by OriHoch** [comment]
the latest tag is only used for local development / docker-compose

the SHA tag is used in production deployments - so that we know exactly what is being deployed

**Comment by iamazeem** [comment]
So, according to this, when we push to `main`, there must be two packages with:

1. GitHub SHA; and,
2. the latest tag.

But, right now, I'm seeing only one with the `latest` tag under [Packages](https://github.com/orgs/CloudWebManage/packages?repo_name=cwm-worker-logger).

**Comment by OriHoch** [comment]
it shows only the latest tag for each package
to see all versions - click on the pacakge, then on the right there is a select-box with view all versions option -
https://github.com/CloudWebManage/cwm-worker-logger/packages/601465/versions

**Comment by iamazeem** [comment]
Got it. Thanks! :)

Is there anything else related to this that needs to be done?
I'll clean up the workflow and finalize it if there's nothing.

**Comment by OriHoch** [comment]
no, the workflows looks fine

**Comment by iamazeem** [comment]
Finalized: https://github.com/CloudWebManage/cwm-worker-logger/runs/1821374433?check_suite_focus=true.
Can be closed now.
